### ISSUE TITLE
Users can view the letters to type.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/typing-test#1]
# Motivation

In order for users to test their typing ability, they must be given a display with the sample text to type.

# Tasks

- [x] Create an HTML file, linking to both a CSS stylesheet and a javascript main script
- [x] Create a landing div and a container div to keep content organized
- [x] Style and position landing/container divs
- [x] Add, style, and position an h1 for a page heading with horizontal rule
- [x] Create an h3 tag with the id "test-text" and center it on the page
- [x] Tweak container dimensions to retain proper rendering
