### ISSUE TITLE
Bug: Result comment renders below container on smaller windows.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/typing-test#11]
# Motivation

Provide a more consistent and visually appealing user experience by maintaining visual consistency on smaller windows.

# Tasks

- [x] Resize the main heading top and bottom margins to occupy less of the test container
- [x] Position the typing test text higher in the container so that the results display on screen in entirety
- [x] Added CSS/JS to expand test container to make room for results
- [x] Raised minimum width of container to prevent title from occupying two lines
- [x] Added small padding to container to prevent text from getting to close to the edge.
