### ISSUE TITLE
User can see prompt for current letter.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/typing-test#3]
# Motivation

Having the currently selected letter be rendered differently allows users to see where they are at in the test and allows for a more clear and fair experience.

# Tasks

- [x] Use the getElementById function in Javascript to access the test-text element and store it in the variable $testText
- [x] Create a function that takes a string and outputs a series of spans containing one letter, contained within one parent span
- [x] Create CSS classes for "correct", "incorrect", and "selected" with appropriate styling
- [x] Tweak string to spanned letters function to add unique IDs to each span
- [x] Create a function to change the class of the currently selected letter to "selected"
- [x] Replace the test text with the string of spans on the page
- [x] Created an event listener to set the selected letter to the first letter of the test text when the DOM loads
