### ISSUE TITLE
User can type a letter and get feedback.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/typing-test#5]
# Motivation

Provide users with realtime feedback as they go through the typing test, allowing them to know which letters were input correctly and incorrectly.

# Tasks

- [x] Add a blinking background to make selected letter stand out
- [x] Add an eventlistener to detect key presses
- [x] Create a function to determine whether the correct letter was input
- [x] Set the key press event actions to include checkInput and increment the testTextIndex count.
- [x] Add the selectLetter function to the keypress event
- [x] Added a conditional statement to not evaluate the shift key as a character input. (Users must still input the correct capitalization)
