### ISSUE TITLE
User can complete a test and view a score.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/typing-test#7]
# Motivation

The test needs an ending and a scoring system to make the experience more engaging and rewarding.

# Tasks

- [x] Add an empty div to contain test results
- [x] Capture the number of correct inputs by adding returns to checkInput function
- [x] Add a conditional statement that checks to see if the testTextIndex count is equal to the length of the test text
- [x] Disable event listener upon reaching the test text length
- [x] Display a result message including the percentage of characters input correctly
- [x] Create multiple display messages based on the results correctness percentage
